### ISSUE TITLE
Add a README to the project

### ISSUE THREAD

**Issue by matt989253** [heig-PDG/mono#32]
## Your feature in two sentences

Add a README on the mono repository

## Description

Add a README that will give information concerning the repository, including team members, website url, and other useful information.

## Deliverable

- [x] A README.md file containing the described information

## Schedule

> The estimated time should be less than 4 hours. Otherwise, it's necessary to split your task in smaller units.

**Estimated time :** 20m
**Actual time :** 20m

**Comment by alexandrepiveteau** [comment]
I've decided not to include the URL in the `README.md` directly, and instead update the repository directly to have the URL of our landing page.
