### ISSUE TITLE
Improve the recipe creation and chat design

### ISSUE THREAD

**Issue by matt989253** [heig-PDG/mono#34]
## Your feature in two sentences

Improve the recipe creation and chat design

## Description
The recipe creation screen and the chat design screen are quite ugly at the moment, try to improve them to have a more friendly and cosy feeling, similar to the home screen.

## Deliverable

- [x] A Figma prototype of the recipe creation and chat screens
- [x] A screenshot of improved the recipe creation screen
- [x] A screenshot of the improved  chat screen

## Schedule

**Estimated time :** 1h30
**Actual time :** 4h34

**Comment by alexandrepiveteau** [comment]
@matt989253 Moving this to the week 3 sprint, because we're still in the process of changing some of the UI.

**Comment by alexandrepiveteau** [comment]
@matt989253 I've spent **2 hours** between yesterday and today to create some new mockups for these screens, which I've added to Clockify. Please enter the time you spent as well.
